[denoising_network_config]
N_spec = 256
N_spat = 128 # 6 * 30
L = 20
B = 256
H = 512
P = 3
X = 6
R = 4
C = 1  # num_speakers
num_channels = 6  # should be consistent with dataloader num_channels
norm_type = 'cLN'
causal = true
mask_nonlinear = 'relu'

[processor_config]
sr = 44100
downsample_factor = 2
nfir = 220

[network_checkpoints]
denoising_left_checkpoint = '../convtasnet_hlm_2stage/denoising_network_22050/model_0180.tar'
denoising_right_checkpoint = '../convtasnet_hlm_2stage/denoising_network_22050/model_0180.tar'
amplification_left_checkpoint = '/home/acp18zt/clarity/clarity/exp_fir_hlm_2stage_2021-05-26 16:51:23/checkpoints/model_amp_best.tar'
amplification_right_checkpoint = '/home/acp18zt/clarity/clarity/exp_fir_hlm_2stage_2021-05-26 16:51:32/checkpoints/model_amp_best.tar'

[listener]
listeners_path = '/fastdata/acp18zt/CLARITY_DATA/clarity_CEC1_data/clarity_data/metadata/listeners.json'
listener_idx = 'L0001'
listener_sr = 44100
src_pos = 'ff'
scenes_listeners = '/fastdata/acp18zt/CLARITY_DATA/clarity_CEC1_data/clarity_data/metadata/scenes_listeners.dev.json'

[inference_dataset]
data_path = '/fastdata/acp18zt/CLARITY_DATA/clarity_CEC1_data/clarity_data/dev/scenes/'
sr = 44100 # 44100
downsample_factor = 2  # consistent with listener
num_channels = 6
norm = false

[inference_dataloader]
batch_size=1
shuffle=false
num_workers = 40

[setup]
do_eval = true
save_dir = './inference_result_nodenopt_1e-4'
